---
name: Collection test and deploy
on: [push, pull_request]
jobs:
  lint-test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        #python-version: [3.8, 3.9]
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v2
        #with:
        #  path: molecule_demo
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt
      - name: Test with molecule
        run: |
          molecule test

  unit-test:
    runs-on: ubuntu-latest
    needs: [lint-test]
    steps:
      - uses: actions/checkout@v2
      - name: Run unit tests
        env:
          VERBOSE: true
        run: |
          echo "init-1"

  build:
    runs-on: ubuntu-latest
    needs: [lint-test, unit-test]
    steps:
      - uses: actions/checkout@v2
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 5
      - name: Show history for debug help
        run: |
          git log --oneline -n 5
      - name: Build binaries and images
        run: |
          #source ./scripts/build.sh
          echo 'x' > test.txt;
      - name: Save images to tar
        run: |
          #source ./scripts/build.sh
          mkdir build
          ansible-galaxy collection build
          mv mtulio-labc-*.tar.gz build/mtulio-labc.tar.gz
      - name: Save artifacts
        uses: actions/upload-artifact@v2
        with:
          #name: build-linux-${{ github.run_id }}
          name: mtulio-labc.tar.gz
          path: |
            build
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

  release-galaxy:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      #- name: Set up Go
      #  uses: actions/setup-go@v2
      #  with:
      #    go-version: 1.16
      #- name: Run GoReleaser
      #  uses: goreleaser/goreleaser-action@v2
      #  with:
      #    version: latest
      #    args: release --rm-dist
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - name: Download binaries and prebuilt images
        uses: actions/download-artifact@v2
        with:
          #name: build-linux-${{ github.run_id }}
          name: mtulio-labc.tar.gz
          #path: build
      #- name: Download binaries and prebuilt images
      #  uses: actions/download-artifact@v2
      #  with:
      #    name: build-windows-${{ github.run_id }}
      #    path: build
      - name: Load images and verify
        run: |
          ansible-galaxy  collection publish ./mtulio-labc.tar.gz --token ${{ secrets.GALAXY_TOKEN }}
